# syntax = docker/dockerfile:1

# Node.jsダウンロード用ビルドステージ（元）
# FROM ruby:3.0.4 AS nodejs

# WORKDIR /tmp

# Node.jsのダウンロード（元）
# RUN curl -LO https://node.js.org/dist/v12.14.1/node-v12.14.1-linux-x64.tar.xz
# RUN tar xvf node-v12.14.1-linux-x64.tar.xz

# xz形式だとエラーとなったためgz形式に変更（これも後でコンパイルのところでエラーになる）
# RUN curl -LO https://node.js.org/dist/v12.14.1/node-v12.14.1-linux-x64.tar.gz
# RUN tar xvf node-v12.14.1-linux-x64.tar.gz
# RUN mv node-v12.14.1-linux-x64 node

# Node.jsダウンロード方法を簡略化してみる
FROM node:12.14.1 AS nodejs

# Railsプロジェクトインストール
FROM ruby:3.0.4

# node.jsをインストールしたイメージからnode.jsをコピーする（元）
# COPY --from=nodejs /tmp/node /opt/node
# ENV PATH /opt/node/bin:$PATH

# node.jsをインストールしたイメージからnode.jsをコピーする（簡略化した場合）
COPY --from=nodejs /usr/local/bin/node /usr/local/bin/node
COPY --from=nodejs /usr/local/lib/node_modules /usr/local/lib/node_modules
RUN ln -s /usr/local/bin/node /usr/local/bin/nodejs


# yarnのインストール（元）
# RUN curl -o- L https://yarnpkg.com/install.sh | bash
# ENV PATH /home/rails/.yarn/bin:/home/rails/.config/yarn/global/node_modules/.bin:$PATH

# nodejsのインストール方法を変えたらyarnインストールでエラーになったためこちらも変更
# yarnをインストールするために必要なパッケージをインストール
RUN apt-get update && apt-get install -y curl

# yarnのインストール（変更）
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install -y yarn

# ruby2.7以上でrails newをするとruby-2.6系で同梱されているbundlerとメジャーバージョンが異なるためbunddlerを実行できなくなる
# そのため、明示的にbundlerを最新にupdateする
RUN gem install bundler

WORKDIR /app

RUN bundle config set path vendor/bundle

# 実行時にコマンド指定がない場合に実行されるコマンド
CMD ["bash"]
